import React, { useState } from 'react';
import { FileText, Plus, Trash2, Printer, Download, Share2 } from 'lucide-react';

const ReceiptGenerator = () => {
  const [businessInfo, setBusinessInfo] = useState(() => {
    const saved = localStorage.getItem('akofa_business_info');
    return saved ? JSON.parse(saved) : {
      name: '',
      phone: '',
      location: ''
    };
  });
  const [items, setItems] = useState([{ description: '', quantity: 1, price: '' }]);
  const [customerName, setCustomerName] = useState('');
  const [showReceipt, setShowReceipt] = useState(false);
  const [receiptNumber, setReceiptNumber] = useState('');

  const addItem = () => {
    setItems([...items, { description: '', quantity: 1, price: '' }]);
  };

  const removeItem = (index) => {
    if (items.length > 1) {
      setItems(items.filter((_, i) => i !== index));
    }
  };

  const updateItem = (index, field, value) => {
    const newItems = [...items];
    newItems[index][field] = value;
    setItems(newItems);
  };

  const calculateTotal = () => {
    return items.reduce((sum, item) => {
      return sum + (parseFloat(item.price) || 0) * (parseInt(item.quantity) || 0);
    }, 0);
  };

  const generateReceipt = () => {
    localStorage.setItem('akofa_business_info', JSON.stringify(businessInfo));
    setReceiptNumber(`RCP-${Date.now().toString().slice(-6)}`);
    setShowReceipt(true);
  };

  const printReceipt = () => {
    window.print();
  };

  const shareReceipt = () => {
    const total = calculateTotal();
    const itemsText = items
      .filter(item => item.description && item.price)
      .map(item => `${item.description}: GHS ${(parseFloat(item.price) * parseInt(item.quantity)).toFixed(2)}`)
      .join('\n');

    const text = `
📄 RECEIPT - ${receiptNumber}
${businessInfo.name}
${businessInfo.location}
Tel: ${businessInfo.phone}

Customer: ${customerName || 'Walk-in'}
Date: ${new Date().toLocaleDateString()}

${itemsText}

TOTAL: GHS ${total.toFixed(2)}

Thank you for your business!
    `.trim();

    if (navigator.share) {
      navigator.share({ text });
    } else {
      window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, '_blank');
    }
  };

  const resetReceipt = () => {
    setShowReceipt(false);
    setItems([{ description: '', quantity: 1, price: '' }]);
    setCustomerName('');
  };

  if (showReceipt) {
    const total = calculateTotal();
    return (
      <div className="bg-slate-800 rounded-xl p-5 border border-slate-700">
        <div className="print-section bg-white text-black rounded-xl p-6 mb-4">
          <div className="text-center mb-4">
            <h2 className="text-xl font-bold">{businessInfo.name || 'Your Business'}</h2>
            {businessInfo.location && <p className="text-sm text-gray-600">{businessInfo.location}</p>}
            {businessInfo.phone && <p className="text-sm text-gray-600">Tel: {businessInfo.phone}</p>}
          </div>

          <div className="border-t border-b border-gray-300 py-2 mb-4">
            <div className="flex justify-between text-sm">
              <span>Receipt #: {receiptNumber}</span>
              <span>{new Date().toLocaleDateString()}</span>
            </div>
            {customerName && (
              <div className="text-sm">Customer: {customerName}</div>
            )}
          </div>

          <div className="mb-4">
            {items.filter(item => item.description && item.price).map((item, index) => (
              <div key={index} className="flex justify-between text-sm py-1">
                <div>
                  <span>{item.description}</span>
                  {item.quantity > 1 && <span className="text-gray-500 ml-1">x{item.quantity}</span>}
                </div>
                <span>GHS {(parseFloat(item.price) * parseInt(item.quantity)).toFixed(2)}</span>
              </div>
            ))}
          </div>

          <div className="border-t border-gray-300 pt-2 mb-4">
            <div className="flex justify-between font-bold text-lg">
              <span>TOTAL</span>
              <span>GHS {total.toFixed(2)}</span>
            </div>
          </div>

          <div className="text-center text-sm text-gray-600">
            <p>Thank you for your business!</p>
            <p className="text-xs mt-1">Generated by Akↄfa Fixit</p>
          </div>
        </div>

        <div className="grid grid-cols-3 gap-2 no-print">
          <button
            onClick={printReceipt}
            className="py-3 bg-blue-600 hover:bg-blue-700 rounded-lg font-medium text-white transition flex items-center justify-center gap-2"
          >
            <Printer className="w-4 h-4" />
            Print
          </button>
          <button
            onClick={shareReceipt}
            className="py-3 bg-green-600 hover:bg-green-700 rounded-lg font-medium text-white transition flex items-center justify-center gap-2"
          >
            <Share2 className="w-4 h-4" />
            Share
          </button>
          <button
            onClick={resetReceipt}
            className="py-3 bg-slate-600 hover:bg-slate-500 rounded-lg font-medium text-white transition"
          >
            New
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="bg-slate-800 rounded-xl p-5 border border-slate-700">
      <div className="flex items-center gap-3 mb-4">
        <div className="w-10 h-10 bg-orange-500/20 rounded-lg flex items-center justify-center">
          <FileText className="w-5 h-5 text-orange-400" />
        </div>
        <div>
          <h3 className="font-bold text-white">Receipt Generator</h3>
          <p className="text-sm text-gray-400">Create and share receipts</p>
        </div>
      </div>

      <div className="space-y-4">
        <div className="bg-slate-700/50 rounded-xl p-4 border border-slate-600">
          <h4 className="font-semibold text-white mb-3">Your Business Info</h4>
          <div className="space-y-2">
            <input
              type="text"
              value={businessInfo.name}
              onChange={(e) => setBusinessInfo(prev => ({ ...prev, name: e.target.value }))}
              placeholder="Business name"
              className="w-full p-2 bg-slate-600 border border-slate-500 rounded-lg text-white placeholder-gray-400 text-sm"
            />
            <div className="grid grid-cols-2 gap-2">
              <input
                type="text"
                value={businessInfo.location}
                onChange={(e) => setBusinessInfo(prev => ({ ...prev, location: e.target.value }))}
                placeholder="Location"
                className="p-2 bg-slate-600 border border-slate-500 rounded-lg text-white placeholder-gray-400 text-sm"
              />
              <input
                type="tel"
                value={businessInfo.phone}
                onChange={(e) => setBusinessInfo(prev => ({ ...prev, phone: e.target.value }))}
                placeholder="Phone"
                className="p-2 bg-slate-600 border border-slate-500 rounded-lg text-white placeholder-gray-400 text-sm"
              />
            </div>
          </div>
        </div>

        <input
          type="text"
          value={customerName}
          onChange={(e) => setCustomerName(e.target.value)}
          placeholder="Customer name (optional)"
          className="w-full p-3 bg-slate-700 border border-slate-600 rounded-lg text-white placeholder-gray-400"
        />

        <div className="space-y-2">
          <div className="flex items-center justify-between">
            <h4 className="font-semibold text-white">Items</h4>
            <button
              onClick={addItem}
              className="p-1 bg-purple-600 hover:bg-purple-700 rounded-lg transition"
            >
              <Plus className="w-4 h-4 text-white" />
            </button>
          </div>
          
          {items.map((item, index) => (
            <div key={index} className="flex gap-2">
              <input
                type="text"
                value={item.description}
                onChange={(e) => updateItem(index, 'description', e.target.value)}
                placeholder="Item"
                className="flex-1 p-2 bg-slate-700 border border-slate-600 rounded-lg text-white placeholder-gray-400 text-sm"
              />
              <input
                type="number"
                value={item.quantity}
                onChange={(e) => updateItem(index, 'quantity', e.target.value)}
                placeholder="Qty"
                className="w-16 p-2 bg-slate-700 border border-slate-600 rounded-lg text-white placeholder-gray-400 text-sm text-center"
              />
              <input
                type="number"
                value={item.price}
                onChange={(e) => updateItem(index, 'price', e.target.value)}
                placeholder="GHS"
                className="w-20 p-2 bg-slate-700 border border-slate-600 rounded-lg text-white placeholder-gray-400 text-sm"
              />
              <button
                onClick={() => removeItem(index)}
                className="p-2 hover:bg-red-500/20 rounded-lg transition"
              >
                <Trash2 className="w-4 h-4 text-red-400" />
              </button>
            </div>
          ))}
        </div>

        <div className="bg-slate-700/50 rounded-xl p-4 flex justify-between items-center">
          <span className="font-semibold text-white">Total:</span>
          <span className="text-2xl font-bold text-green-400">GHS {calculateTotal().toFixed(2)}</span>
        </div>

        <button
          onClick={generateReceipt}
          className="w-full py-4 bg-orange-600 hover:bg-orange-700 rounded-xl font-semibold text-white transition"
        >
          Generate Receipt
        </button>
      </div>
    </div>
  );
};

export default ReceiptGenerator;
